### ISSUE TITLE
Collaboration With PteroApiWraooer

### ISSUE THREAD

**Issue by arnav335** [InnateAlpaca/pterosocket#5]
I have recently made an API wrapper for pterodactyl called- 'pteroApiWrapper' for nodejs, if you agree we can collaborate and make the best API wrapper ever of pterodactyl panel in nodeJS, contact me on discord - Arnav G. Or contact me on email- anonyoneop@gmail.com or just reply to this issue

**Comment by InnateAlpaca** [comment]
Hello, let's discuss that in discord. This is my dev-server https://discord.gg/A2SDjxQshJ
